apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-sleep
data:
  config.json: |
    {"scale_up":"08:30","scale_down":"06:31","exclude_day":"","min_replicas":"0.3,2","target_namespace": "nginx-ingress","target_hpa_namespace": "","exclude_namespace": "","exclude_hpa": "","scale_up_delay":15,"scale_up_timeout":1800}